<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstadoMunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $estados = [
            ['est_nombre' => 'Amazonas'],
            ['est_nombre' => 'Anzoátegui'],
            ['est_nombre' => 'Apure'],
            ['est_nombre' => 'Aragua'],
            ['est_nombre' => 'Barinas'],
            ['est_nombre' => 'Bolívar'],
            ['est_nombre' => 'Carabobo'],
            ['est_nombre' => 'Cojedes'],
            ['est_nombre' => 'Delta Amacuro'],
            ['est_nombre' => 'Distrito Capital'],
            ['est_nombre' => 'Falcón'],
            ['est_nombre' => 'Guárico'],
            ['est_nombre' => 'Lara'],
            ['est_nombre' => 'Mérida'],
            ['est_nombre' => 'Miranda'],
            ['est_nombre' => 'Monagas'],
            ['est_nombre' => 'Nueva Esparta'],
            ['est_nombre' => 'Portuguesa'],
            ['est_nombre' => 'Sucre'],
            ['est_nombre' => 'Táchira'],
            ['est_nombre' => 'Trujillo'],
            ['est_nombre' => 'La Guaira'],
            ['est_nombre' => 'Yaracuy'],
            ['est_nombre' => 'Zulia'],
        ];

        DB::table('estados')->insert($estados);

        $municipios = [
            // Amazonas (1-7)
            ['mun_nombre' => 'Alto Orinoco', 'est_codigo' => 1],
            ['mun_nombre' => 'Atabapo', 'est_codigo' => 1],
            ['mun_nombre' => 'Atures', 'est_codigo' => 1],
            ['mun_nombre' => 'Autana', 'est_codigo' => 1],
            ['mun_nombre' => 'Manapiare', 'est_codigo' => 1],
            ['mun_nombre' => 'Maroa', 'est_codigo' => 1],
            ['mun_nombre' => 'Río Negro', 'est_codigo' => 1],
            // Anzoátegui (8-28)
            ['mun_nombre' => 'Anaco', 'est_codigo' => 2],
            ['mun_nombre' => 'Aragua', 'est_codigo' => 2],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 2],
            ['mun_nombre' => 'Bruzual', 'est_codigo' => 2],
            ['mun_nombre' => 'Cajigal', 'est_codigo' => 2],
            ['mun_nombre' => 'Carvajal', 'est_codigo' => 2],
            ['mun_nombre' => 'Diego Bautista Urbaneja', 'est_codigo' => 2],
            ['mun_nombre' => 'Freites', 'est_codigo' => 2],
            ['mun_nombre' => 'Guanipa', 'est_codigo' => 2],
            ['mun_nombre' => 'Guanta', 'est_codigo' => 2],
            ['mun_nombre' => 'Independencia', 'est_codigo' => 2],
            ['mun_nombre' => 'Libertad', 'est_codigo' => 2],
            ['mun_nombre' => 'McGregor', 'est_codigo' => 2],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 2],
            ['mun_nombre' => 'Monagas', 'est_codigo' => 2],
            ['mun_nombre' => 'Peñalver', 'est_codigo' => 2],
            ['mun_nombre' => 'Píritu', 'est_codigo' => 2],
            ['mun_nombre' => 'San Juan de Capistrano', 'est_codigo' => 2],
            ['mun_nombre' => 'Santa Ana', 'est_codigo' => 2],
            ['mun_nombre' => 'Simón Rodríguez', 'est_codigo' => 2],
            ['mun_nombre' => 'Sotillo', 'est_codigo' => 2],
            // Apure (29-35)
            ['mun_nombre' => 'Achaguas', 'est_codigo' => 3],
            ['mun_nombre' => 'Biruaca', 'est_codigo' => 3],
            ['mun_nombre' => 'Muñoz', 'est_codigo' => 3],
            ['mun_nombre' => 'Páez', 'est_codigo' => 3],
            ['mun_nombre' => 'Pedro Camejo', 'est_codigo' => 3],
            ['mun_nombre' => 'Rómulo Gallegos', 'est_codigo' => 3],
            ['mun_nombre' => 'San Fernando', 'est_codigo' => 3],
            // Aragua (36-53)
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 4],
            ['mun_nombre' => 'Camatagua', 'est_codigo' => 4],
            ['mun_nombre' => 'Francisco Linares Alcántara', 'est_codigo' => 4],
            ['mun_nombre' => 'Girardot', 'est_codigo' => 4],
            ['mun_nombre' => 'José Ángel Lamas', 'est_codigo' => 4],
            ['mun_nombre' => 'José Félix Ribas', 'est_codigo' => 4],
            ['mun_nombre' => 'José Rafael Revenga', 'est_codigo' => 4],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 4],
            ['mun_nombre' => 'Mario Briceño Iragorry', 'est_codigo' => 4],
            ['mun_nombre' => 'Ocumare de la Costa de Oro', 'est_codigo' => 4],
            ['mun_nombre' => 'San Casimiro', 'est_codigo' => 4],
            ['mun_nombre' => 'San Sebastián', 'est_codigo' => 4],
            ['mun_nombre' => 'Santiago Mariño', 'est_codigo' => 4],
            ['mun_nombre' => 'Santos Michelena', 'est_codigo' => 4],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 4],
            ['mun_nombre' => 'Tovar', 'est_codigo' => 4],
            ['mun_nombre' => 'Urdaneta', 'est_codigo' => 4],
            ['mun_nombre' => 'Zamora', 'est_codigo' => 4],
            // Barinas (54-65)
            ['mun_nombre' => 'Alberto Arvelo Torrealba', 'est_codigo' => 5],
            ['mun_nombre' => 'Andrés Eloy Blanco', 'est_codigo' => 5],
            ['mun_nombre' => 'Antonio José de Sucre', 'est_codigo' => 5],
            ['mun_nombre' => 'Arismendi', 'est_codigo' => 5],
            ['mun_nombre' => 'Barinas', 'est_codigo' => 5],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 5],
            ['mun_nombre' => 'Cruz Paredes', 'est_codigo' => 5],
            ['mun_nombre' => 'Ezequiel Zamora', 'est_codigo' => 5],
            ['mun_nombre' => 'Obispos', 'est_codigo' => 5],
            ['mun_nombre' => 'Pedraza', 'est_codigo' => 5],
            ['mun_nombre' => 'Rojas', 'est_codigo' => 5],
            ['mun_nombre' => 'Sosa', 'est_codigo' => 5],
            // Bolívar (66-76)
            ['mun_nombre' => 'Caroní', 'est_codigo' => 6],
            ['mun_nombre' => 'Cedeño', 'est_codigo' => 6],
            ['mun_nombre' => 'El Callao', 'est_codigo' => 6],
            ['mun_nombre' => 'Gran Sabana', 'est_codigo' => 6],
            ['mun_nombre' => 'Heres', 'est_codigo' => 6],
            ['mun_nombre' => 'Piar', 'est_codigo' => 6],
            ['mun_nombre' => 'Padre Pedro Chien', 'est_codigo' => 6],
            ['mun_nombre' => 'Roscio', 'est_codigo' => 6],
            ['mun_nombre' => 'Sifontes', 'est_codigo' => 6],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 6],
            ['mun_nombre' => 'Raúl Leoni', 'est_codigo' => 6],
            // Carabobo (77-90)
            ['mun_nombre' => 'Bejuma', 'est_codigo' => 7],
            ['mun_nombre' => 'Carlos Arvelo', 'est_codigo' => 7],
            ['mun_nombre' => 'Diego Ibarra', 'est_codigo' => 7],
            ['mun_nombre' => 'Guacara', 'est_codigo' => 7],
            ['mun_nombre' => 'Juan José Mora', 'est_codigo' => 7],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 7],
            ['mun_nombre' => 'Los Guayos', 'est_codigo' => 7],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 7],
            ['mun_nombre' => 'Montalbán', 'est_codigo' => 7],
            ['mun_nombre' => 'Naguanagua', 'est_codigo' => 7],
            ['mun_nombre' => 'Puerto Cabello', 'est_codigo' => 7],
            ['mun_nombre' => 'San Diego', 'est_codigo' => 7],
            ['mun_nombre' => 'San Joaquín', 'est_codigo' => 7],
            ['mun_nombre' => 'Valencia', 'est_codigo' => 7],
            // Cojedes (91-99)
            ['mun_nombre' => 'Anzoátegui', 'est_codigo' => 8],
            ['mun_nombre' => 'Ezequiel Zamora', 'est_codigo' => 8],
            ['mun_nombre' => 'Falcón', 'est_codigo' => 8],
            ['mun_nombre' => 'Girardot', 'est_codigo' => 8],
            ['mun_nombre' => 'Lima Blanco', 'est_codigo' => 8],
            ['mun_nombre' => 'Pao de San Juan Bautista', 'est_codigo' => 8],
            ['mun_nombre' => 'Ricaurte', 'est_codigo' => 8],
            ['mun_nombre' => 'Rómulo Gallegos', 'est_codigo' => 8],
            ['mun_nombre' => 'Tinaco', 'est_codigo' => 8],
            // Delta Amacuro (100-103)
            ['mun_nombre' => 'Antonio Díaz', 'est_codigo' => 9],
            ['mun_nombre' => 'Casacoima', 'est_codigo' => 9],
            ['mun_nombre' => 'Pedernales', 'est_codigo' => 9],
            ['mun_nombre' => 'Tucupita', 'est_codigo' => 9],
            // Distrito Capital (104)
            ['mun_nombre' => 'Libertador', 'est_codigo' => 10],
            // Falcón (105-129)
            ['mun_nombre' => 'Acosta', 'est_codigo' => 11],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 11],
            ['mun_nombre' => 'Buchivacoa', 'est_codigo' => 11],
            ['mun_nombre' => 'Cacique Manaure', 'est_codigo' => 11],
            ['mun_nombre' => 'Carirubana', 'est_codigo' => 11],
            ['mun_nombre' => 'Colina', 'est_codigo' => 11],
            ['mun_nombre' => 'Dabajuro', 'est_codigo' => 11],
            ['mun_nombre' => 'Democracia', 'est_codigo' => 11],
            ['mun_nombre' => 'Falcón', 'est_codigo' => 11],
            ['mun_nombre' => 'Federación', 'est_codigo' => 11],
            ['mun_nombre' => 'Jacura', 'est_codigo' => 11],
            ['mun_nombre' => 'Los Taques', 'est_codigo' => 11],
            ['mun_nombre' => 'Mauroa', 'est_codigo' => 11],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 11],
            ['mun_nombre' => 'Monseñor Iturriza', 'est_codigo' => 11],
            ['mun_nombre' => 'Palmasola', 'est_codigo' => 11],
            ['mun_nombre' => 'Petit', 'est_codigo' => 11],
            ['mun_nombre' => 'Píritu', 'est_codigo' => 11],
            ['mun_nombre' => 'San Francisco', 'est_codigo' => 11],
            ['mun_nombre' => 'Silva', 'est_codigo' => 11],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 11],
            ['mun_nombre' => 'Tocópero', 'est_codigo' => 11],
            ['mun_nombre' => 'Unión', 'est_codigo' => 11],
            ['mun_nombre' => 'Urumaco', 'est_codigo' => 11],
            ['mun_nombre' => 'Zamora', 'est_codigo' => 11],
            // Guárico (130-144)
            ['mun_nombre' => 'Camaguán', 'est_codigo' => 12],
            ['mun_nombre' => 'Chaguaramas', 'est_codigo' => 12],
            ['mun_nombre' => 'El Socorro', 'est_codigo' => 12],
            ['mun_nombre' => 'Francisco de Miranda', 'est_codigo' => 12],
            ['mun_nombre' => 'José Félix Ribas', 'est_codigo' => 12],
            ['mun_nombre' => 'José Tadeo Monagas', 'est_codigo' => 12],
            ['mun_nombre' => 'Juan Germán Roscio', 'est_codigo' => 12],
            ['mun_nombre' => 'Julián Mellado', 'est_codigo' => 12],
            ['mun_nombre' => 'Las Mercedes', 'est_codigo' => 12],
            ['mun_nombre' => 'Ortiz', 'est_codigo' => 12],
            ['mun_nombre' => 'Pedro Zaraza', 'est_codigo' => 12],
            ['mun_nombre' => 'San Gerónimo de Guayabal', 'est_codigo' => 12],
            ['mun_nombre' => 'San José de Guaribe', 'est_codigo' => 12],
            ['mun_nombre' => 'Santa María de Ipire', 'est_codigo' => 12],
            // Lara (145-154)
            ['mun_nombre' => 'Andrés Eloy Blanco', 'est_codigo' => 13],
            ['mun_nombre' => 'Crespo', 'est_codigo' => 13],
            ['mun_nombre' => 'Iribarren', 'est_codigo' => 13],
            ['mun_nombre' => 'Jiménez', 'est_codigo' => 13],
            ['mun_nombre' => 'Morán', 'est_codigo' => 13],
            ['mun_nombre' => 'Palavecino', 'est_codigo' => 13],
            ['mun_nombre' => 'Simón Planas', 'est_codigo' => 13],
            ['mun_nombre' => 'Torres', 'est_codigo' => 13],
            ['mun_nombre' => 'Urdaneta', 'est_codigo' => 13],
            // Mérida (155-177)
            ['mun_nombre' => 'Alberto Adriani', 'est_codigo' => 14],
            ['mun_nombre' => 'Andrés Bello', 'est_codigo' => 14],
            ['mun_nombre' => 'Antonio Pinto Salinas', 'est_codigo' => 14],
            ['mun_nombre' => 'Aricagua', 'est_codigo' => 14],
            ['mun_nombre' => 'Arzobispo Chacón', 'est_codigo' => 14],
            ['mun_nombre' => 'Campo Elías', 'est_codigo' => 14],
            ['mun_nombre' => 'Caracciolo Parra Olmedo', 'est_codigo' => 14],
            ['mun_nombre' => 'Cardenal Quintero', 'est_codigo' => 14],
            ['mun_nombre' => 'Guaraque', 'est_codigo' => 14],
            ['mun_nombre' => 'Julio César Salas', 'est_codigo' => 14],
            ['mun_nombre' => 'Justo Briceño', 'est_codigo' => 14],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 14],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 14],
            ['mun_nombre' => 'Obispo Ramos de Lora', 'est_codigo' => 14],
            ['mun_nombre' => 'Padre Noguera', 'est_codigo' => 14],
            ['mun_nombre' => 'Pueblo Llano', 'est_codigo' => 14],
            ['mun_nombre' => 'Rangel', 'est_codigo' => 14],
            ['mun_nombre' => 'Rivas Dávila', 'est_codigo' => 14],
            ['mun_nombre' => 'Santos Marquina', 'est_codigo' => 14],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 14],
            ['mun_nombre' => 'Tovar', 'est_codigo' => 14],
            ['mun_nombre' => 'Tulio Febres Cordero', 'est_codigo' => 14],
            ['mun_nombre' => 'Zea', 'est_codigo' => 14],
            // Miranda (178-198)
            ['mun_nombre' => 'Acevedo', 'est_codigo' => 15],
            ['mun_nombre' => 'Andrés Bello', 'est_codigo' => 15],
            ['mun_nombre' => 'Baruta', 'est_codigo' => 15],
            ['mun_nombre' => 'Brión', 'est_codigo' => 15],
            ['mun_nombre' => 'Buroz', 'est_codigo' => 15],
            ['mun_nombre' => 'Carrizal', 'est_codigo' => 15],
            ['mun_nombre' => 'Chacao', 'est_codigo' => 15],
            ['mun_nombre' => 'Cristóbal Rojas', 'est_codigo' => 15],
            ['mun_nombre' => 'El Hatillo', 'est_codigo' => 15],
            ['mun_nombre' => 'Guaicaipuro', 'est_codigo' => 15],
            ['mun_nombre' => 'Independencia', 'est_codigo' => 15],
            ['mun_nombre' => 'Lander', 'est_codigo' => 15],
            ['mun_nombre' => 'Los Salias', 'est_codigo' => 15],
            ['mun_nombre' => 'Páez', 'est_codigo' => 15],
            ['mun_nombre' => 'Paz Castillo', 'est_codigo' => 15],
            ['mun_nombre' => 'Pedro Gual', 'est_codigo' => 15],
            ['mun_nombre' => 'Plaza', 'est_codigo' => 15],
            ['mun_nombre' => 'Simón Bolívar', 'est_codigo' => 15],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 15],
            ['mun_nombre' => 'Urdaneta', 'est_codigo' => 15],
            ['mun_nombre' => 'Zamora', 'est_codigo' => 15],
            // Monagas (199-211)
            ['mun_nombre' => 'Acosta', 'est_codigo' => 16],
            ['mun_nombre' => 'Aguasay', 'est_codigo' => 16],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 16],
            ['mun_nombre' => 'Caripe', 'est_codigo' => 16],
            ['mun_nombre' => 'Cedeño', 'est_codigo' => 16],
            ['mun_nombre' => 'Ezequiel Zamora', 'est_codigo' => 16],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 16],
            ['mun_nombre' => 'Maturín', 'est_codigo' => 16],
            ['mun_nombre' => 'Piar', 'est_codigo' => 16],
            ['mun_nombre' => 'Punceres', 'est_codigo' => 16],
            ['mun_nombre' => 'Santa Bárbara', 'est_codigo' => 16],
            ['mun_nombre' => 'Sotillo', 'est_codigo' => 16],
            ['mun_nombre' => 'Uracoa', 'est_codigo' => 16],
            // Nueva Esparta (212-222)
            ['mun_nombre' => 'Antolín del Campo', 'est_codigo' => 17],
            ['mun_nombre' => 'Arismendi', 'est_codigo' => 17],
            ['mun_nombre' => 'Díaz', 'est_codigo' => 17],
            ['mun_nombre' => 'García', 'est_codigo' => 17],
            ['mun_nombre' => 'Gómez', 'est_codigo' => 17],
            ['mun_nombre' => 'Maneiro', 'est_codigo' => 17],
            ['mun_nombre' => 'Marcano', 'est_codigo' => 17],
            ['mun_nombre' => 'Mariño', 'est_codigo' => 17],
            ['mun_nombre' => 'Península de Macanao', 'est_codigo' => 17],
            ['mun_nombre' => 'Tubores', 'est_codigo' => 17],
            ['mun_nombre' => 'Villalba', 'est_codigo' => 17],
            // Portuguesa (223-236)
            ['mun_nombre' => 'Agua Blanca', 'est_codigo' => 18],
            ['mun_nombre' => 'Araure', 'est_codigo' => 18],
            ['mun_nombre' => 'Esteller', 'est_codigo' => 18],
            ['mun_nombre' => 'Guanare', 'est_codigo' => 18],
            ['mun_nombre' => 'Guanarito', 'est_codigo' => 18],
            ['mun_nombre' => 'Monseñor José Vicente de Unda', 'est_codigo' => 18],
            ['mun_nombre' => 'Ospino', 'est_codigo' => 18],
            ['mun_nombre' => 'Páez', 'est_codigo' => 18],
            ['mun_nombre' => 'Papelón', 'est_codigo' => 18],
            ['mun_nombre' => 'San Genaro de Boconoíto', 'est_codigo' => 18],
            ['mun_nombre' => 'San Rafael de Onoto', 'est_codigo' => 18],
            ['mun_nombre' => 'Santa Rosalía', 'est_codigo' => 18],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 18],
            ['mun_nombre' => 'Turén', 'est_codigo' => 18],
            // Sucre (237-251)
            ['mun_nombre' => 'Andrés Eloy Blanco', 'est_codigo' => 19],
            ['mun_nombre' => 'Andrés Mata', 'est_codigo' => 19],
            ['mun_nombre' => 'Arismendi', 'est_codigo' => 19],
            ['mun_nombre' => 'Benítez', 'est_codigo' => 19],
            ['mun_nombre' => 'Bermúdez', 'est_codigo' => 19],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 19],
            ['mun_nombre' => 'Cajigal', 'est_codigo' => 19],
            ['mun_nombre' => 'Cruz Salmerón Acosta', 'est_codigo' => 19],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 19],
            ['mun_nombre' => 'Mariño', 'est_codigo' => 19],
            ['mun_nombre' => 'Mejía', 'est_codigo' => 19],
            ['mun_nombre' => 'Montes', 'est_codigo' => 19],
            ['mun_nombre' => 'Ribero', 'est_codigo' => 19],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 19],
            ['mun_nombre' => 'Valdéz', 'est_codigo' => 19],
            // Táchira (252-280)
            ['mun_nombre' => 'Andrés Bello', 'est_codigo' => 20],
            ['mun_nombre' => 'Antonio Rómulo Costa', 'est_codigo' => 20],
            ['mun_nombre' => 'Ayacucho', 'est_codigo' => 20],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 20],
            ['mun_nombre' => 'Cárdenas', 'est_codigo' => 20],
            ['mun_nombre' => 'Córdoba', 'est_codigo' => 20],
            ['mun_nombre' => 'Fernández Feo', 'est_codigo' => 20],
            ['mun_nombre' => 'Francisco de Miranda', 'est_codigo' => 20],
            ['mun_nombre' => 'García de Hevia', 'est_codigo' => 20],
            ['mun_nombre' => 'Guásimos', 'est_codigo' => 20],
            ['mun_nombre' => 'Independencia', 'est_codigo' => 20],
            ['mun_nombre' => 'Jáuregui', 'est_codigo' => 20],
            ['mun_nombre' => 'José María Vargas', 'est_codigo' => 20],
            ['mun_nombre' => 'Junín', 'est_codigo' => 20],
            ['mun_nombre' => 'Libertad', 'est_codigo' => 20],
            ['mun_nombre' => 'Libertador', 'est_codigo' => 20],
            ['mun_nombre' => 'Lobatera', 'est_codigo' => 20],
            ['mun_nombre' => 'Michelena', 'est_codigo' => 20],
            ['mun_nombre' => 'Panamericano', 'est_codigo' => 20],
            ['mun_nombre' => 'Pedro María Ureña', 'est_codigo' => 20],
            ['mun_nombre' => 'Rafael Urdaneta', 'est_codigo' => 20],
            ['mun_nombre' => 'Samuel Darío Maldonado', 'est_codigo' => 20],
            ['mun_nombre' => 'San Cristóbal', 'est_codigo' => 20],
            ['mun_nombre' => 'San Judas Tadeo', 'est_codigo' => 20],
            ['mun_nombre' => 'Seboruco', 'est_codigo' => 20],
            ['mun_nombre' => 'Simón Rodríguez', 'est_codigo' => 20],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 20],
            ['mun_nombre' => 'Torbes', 'est_codigo' => 20],
            ['mun_nombre' => 'Uribante', 'est_codigo' => 20],
            // Trujillo (281-300)
            ['mun_nombre' => 'Andrés Bello', 'est_codigo' => 21],
            ['mun_nombre' => 'Boconó', 'est_codigo' => 21],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 21],
            ['mun_nombre' => 'Candelaria', 'est_codigo' => 21],
            ['mun_nombre' => 'Carache', 'est_codigo' => 21],
            ['mun_nombre' => 'Escuque', 'est_codigo' => 21],
            ['mun_nombre' => 'José Felipe Márquez Cañizales', 'est_codigo' => 21],
            ['mun_nombre' => 'Juan Vicente Campo Elías', 'est_codigo' => 21],
            ['mun_nombre' => 'La Ceiba', 'est_codigo' => 21],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 21],
            ['mun_nombre' => 'Monte Carmelo', 'est_codigo' => 21],
            ['mun_nombre' => 'Motatán', 'est_codigo' => 21],
            ['mun_nombre' => 'Pampán', 'est_codigo' => 21],
            ['mun_nombre' => 'Pampanito', 'est_codigo' => 21],
            ['mun_nombre' => 'Rafael Rangel', 'est_codigo' => 21],
            ['mun_nombre' => 'San Rafael de Carvajal', 'est_codigo' => 21],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 21],
            ['mun_nombre' => 'Trujillo', 'est_codigo' => 21],
            ['mun_nombre' => 'Urdaneta', 'est_codigo' => 21],
            ['mun_nombre' => 'Valera', 'est_codigo' => 21],
            // La Guaira (301)
            ['mun_nombre' => 'Vargas', 'est_codigo' => 22],
            // Yaracuy (302-315)
            ['mun_nombre' => 'Arístides Bastidas', 'est_codigo' => 23],
            ['mun_nombre' => 'Bolívar', 'est_codigo' => 23],
            ['mun_nombre' => 'Bruzual', 'est_codigo' => 23],
            ['mun_nombre' => 'Cocorote', 'est_codigo' => 23],
            ['mun_nombre' => 'Independencia', 'est_codigo' => 23],
            ['mun_nombre' => 'José Antonio Páez', 'est_codigo' => 23],
            ['mun_nombre' => 'La Trinidad', 'est_codigo' => 23],
            ['mun_nombre' => 'Manuel Monge', 'est_codigo' => 23],
            ['mun_nombre' => 'Nirgua', 'est_codigo' => 23],
            ['mun_nombre' => 'Peña', 'est_codigo' => 23],
            ['mun_nombre' => 'San Felipe', 'est_codigo' => 23],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 23],
            ['mun_nombre' => 'Urachiche', 'est_codigo' => 23],
            ['mun_nombre' => 'Veroes', 'est_codigo' => 23],
            // Zulia (316-336)
            ['mun_nombre' => 'Almirante Padilla', 'est_codigo' => 24],
            ['mun_nombre' => 'Baralt', 'est_codigo' => 24],
            ['mun_nombre' => 'Cabimas', 'est_codigo' => 24],
            ['mun_nombre' => 'Catatumbo', 'est_codigo' => 24],
            ['mun_nombre' => 'Colón', 'est_codigo' => 24],
            ['mun_nombre' => 'Francisco Javier Pulgar', 'est_codigo' => 24],
            ['mun_nombre' => 'Guajira', 'est_codigo' => 24],
            ['mun_nombre' => 'Jesús Enrique Lossada', 'est_codigo' => 24],
            ['mun_nombre' => 'Jesús María Semprún', 'est_codigo' => 24],
            ['mun_nombre' => 'La Cañada de Urdaneta', 'est_codigo' => 24],
            ['mun_nombre' => 'Lagunillas', 'est_codigo' => 24],
            ['mun_nombre' => 'Machiques de Perijá', 'est_codigo' => 24],
            ['mun_nombre' => 'Mara', 'est_codigo' => 24],
            ['mun_nombre' => 'Maracaibo', 'est_codigo' => 24],
            ['mun_nombre' => 'Miranda', 'est_codigo' => 24],
            ['mun_nombre' => 'Rosario de Perijá', 'est_codigo' => 24],
            ['mun_nombre' => 'San Francisco', 'est_codigo' => 24],
            ['mun_nombre' => 'Santa Rita', 'est_codigo' => 24],
            ['mun_nombre' => 'Simón Bolívar', 'est_codigo' => 24],
            ['mun_nombre' => 'Sucre', 'est_codigo' => 24],
            ['mun_nombre' => 'Valmore Rodríguez', 'est_codigo' => 24],
        ];

        DB::table('municipios')->insert($municipios);
    }
}
